apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githubservers.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: githubservers
    singular: githubserver
    kind: GithubServer
    categories:
    - jenkins
    - ci
    - github
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - repositoryUrl
          properties:
            apiUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
              nullable: true
            username:
              type: string
              nullable: false
            organization:
              type: string
              nullable: false
            credentialsId:
              type: string
              nullable: true
            manageHooks:
              type: boolean
              nullable: true
#
#
#data:
#  apiUrl: https://api.github.com
#  organization: agilestacks
#  credentialsId: asibot
#  username: asibot
