apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: credentials.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: credentials
    singular: cred
    kind: Credentials
    shortNames: [creds]
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          properties:
            id:
              type: string
            scope:
              type: string
            domain:
              type: string
              pattern: '((www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}|GLOBAL|global)'
            description:
              type: string
            usernamePassword:
              properties:
                username:
                  type: string
                  nullable: false
                password:
                  type: object
                  nullable: false
                  properties:
                    secretKeyRef:
                      type: object
                      nullable: false
                      properties:
                        name:
                          type: string
                          nullable: false
                        key:
                          type: string
                          nullable: false
            secretString:
              properties:
                secretKeyRef:
                  type: object
                  nullable: false
                  properties:
                    name:
                      type: string
                      nullable: false
                    key:
                      type: string
                      nullable: false
