apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuberntes.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: kubernetes
    singular: k8s
    kind: KubernetesCluster
    categories:
    - jenkins
    - ci
    - kubernetes
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - baseUrl
          properties:
            baseUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
              nullable: false
            name:
              type: string
            credentialsId:
              type: string
