apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: slacks.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: slacks
    singular: slack
    kind: Slack
    categories:
    - jenkins
    - ci
    - slack
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - baseUrl
          - botUser
          - buildServerUrl
          - room
          - sendAs
          - teamDomain
          - credentialsId
          properties:
            baseUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
            botUser:
              type: boolean
            buildServerUrl:
              type: string
            room:
              type: string
            sendAs:
              type: string
            teamDomain:
              type: string
            credentialsId:
              type: string
