apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
    - jp
    - pipe
    - pipes
    - wf
    - jenkinspipelines
    - jenkinspipeline
    - workflows
    - workflow
    categories:
    - jenkins
    - ci
    - pipeline
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ['repositoryUrl']
          properties:
            repositoryUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
              description: "URL to the source code repository with application and pipeline"
            name:
              type: string
              description: "Name of the Jenkins job"
            branchSpec:
              type: string
              description: "SCM branch spec. Defaults to master"
            pipeline:
              type: string
              description: "Reference to Jenkinsfile in the repository"
            credentialsId:
              type: string
              description: "Reference to Jenkinsfile in the repository"
            folder:
              type: string
              description: "Create a Jenkins folder and put pipeline there if not empty"
            startBuild:
              type: boolean
              description: "If true, then start build after pipeline will has been created"
            origin:
              type: string
            delay:
              type: number
              description: "Number of seconds to delay first build (to give configuration to settle down)"
