apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pipelines.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    categories:
    - jenkins
    - ci
    - pipeline
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
          - repositoryUrl
          properties:
            repositoryUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
              nullable: false
            name:
              type: string
              nullable: true
            branchSpec:
              type: string
            pipeline:
              type: string
            credentialsId:
              type: string
              nullable: true
            folder:
              type: string
              nullable: true
            startBuild:
              type: boolean
            origin:
              type: string
            delay:
              type: number
              nullable: true
