---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret-text
  namespace: jenkins
  labels:
    provider: agilestacks.com
    project: jenkins
    qualifier: credentials
data:
  secret: c3VwZXJzZWNyZXQK
---
apiVersion: "jenkins.agilestacks.com/v1"
kind: Credentials
metadata:
  name: test-secret-text
spec:
  domain: global
  description: Test secret text
  secretString:
    secretKeyRef:
      name: test-secret-text
      key: secret
