---
apiVersion: "jenkins.agilestacks.com/v1"
kind: Credentials
metadata:
  name: test
spec:
  domain: global
  description: Test credentials
  usernamePassword:
    username: test
    password:
      secretKeyRef:
        name: test-secret
        key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: jenkins
  labels:
    provider: agilestacks.com
    project: jenkins
    qualifier: credentials
data:
  password: c3VwZXJzZWNyZXQK
