---
apiVersion: "jenkins.agilestacks.com/v1"
kind: Pipeline
metadata:
  name: myreactjs
spec:
  repositoryUrl: "https://github.com/agilestacks/applications.git"
  folder: sample-pipelines
  credentialsId: mygithub-token
  parameters:
  - name: APPLICATION_NAME
    type: string
    defaultValue: hello-kitty
    description: Name of the application to deploy
  - name: CONTEXT_PATH
    type: string
    defaultValue:
    description: Context path of the applicaiton (empty means root)
  - name: STATE_FILE
    type: string
    defaultValue: s3://terraform.agilestacks.com/antondo2.kubernetes.delivery/hub/prod/hub.state
    description: Full path to the backend stack state file
  - name: TEST_BOOL
    type: boolean
    defaultValue: true
    description: Testing true or false
