apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githuborgs.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: githuborgs
    singular: githuborg
    kind: GithubOrganization
    categories:
    - jenkins
    - ci
    - github
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - repositoryUrl
          properties:
            apiUrl:
              type: string
              pattern: '(https?)(:\/\/)(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)'
            username:
              type: string
            organization:
              type: string
            credentialsId:
              type: string
            scanCredentialsId:
              type: string
            description:
              type: string
            scheduleBuild:
              type: boolean
