apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githuborgs.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: githuborgs
    singular: githuborg
    kind: GithubOrganization
    categories:
    - jenkins
    - ci
    - github
    shortNames:
    - org
    - orgs
    - organization
    - organizations
    - github-organizations
    - githuborganizations
    - github-organization
    - githuborganization
    - github-orgs
    - gh-orgs
    - ghorgs
    - ghorg
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - organization
          properties:
            organization:
              type: string
            credentialsId:
              type: string
            scanCredentialsId:
              type: string
            description:
              type: string
            scheduleBuild:
              type: boolean
