apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: githuborganizations.jenkins.agilestacks.com
spec:
  group: jenkins.agilestacks.com
  version: v1
  scope: Namespaced
  names:
    plural: githuborganizations
    singular: githuborganization
    kind: GithubOrganization
    shortNames:
    - org
    - orgs
    - organization
    - organizations
    - github-organizations
    - github-organization
    - githuborg
    - githuborgs
    - github-orgs
    - gh-org
    - gh-orgs
    - ghorgs
    - ghorg
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - organization
          properties:
            organization:
              type: string
            credentialsId:
              type: string
            scanCredentialsId:
              type: string
            description:
              type: string
            scheduleBuild:
              type: boolean
